deployment:
  name: web
  replicas: 1
  port: 3000
  image:
    repository: myacr12067.azurecr.io/web-app
    tag: "v1.0.3"
    pullPolicy: IfNotPresent
  imagePullSecretName: acr-pull

  probes:
    path: /health
    port: 3000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

service:
  name: web-service
  port: 80
  type: LoadBalancer

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 50

env:
  NODE_ENV: "production"
  API_URL: "http://api-service.api.svc.cluster.local:3001" #for separate repos when we split 

# secret for future
secrets:
  API_KEY: ""
