deployment:
  name: api
  replicas: 1
  port: 3001
  image:
    repository: myacr12067.azurecr.io/api-app
    tag: "v1.0.1"
    pullPolicy: IfNotPresent
  imagePullSecretName: acr-pull

  probes:
    path: /health
    port: 3001

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

service:
  name: api-service
  port: 3001
  type: ClusterIP

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 50

env:
  NODE_ENV: "production"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"

# will fill later
secrets:
  DB_USER: ""
  DB_PASS: ""
