deployment:
  name: api
  replicas: 1
  port: 3001
  image:
    repository: acrf40955.azurecr.io/api-app
    tag: "3cbcea4"
    pullPolicy: IfNotPresent

  probes:
    readiness:
      path: /health
      port: 3001
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 10
    liveness:
      path: /health
      port: 3001
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 10

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

service:
  name: api-service
  port: 3001
  type: ClusterIP

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 50

env:
  NODE_ENV: "production"
  PORT: "3001"

secrets:
  DB_HOST: ""
  DB_NAME: ""
  DB_USER: ""
  DB_PASS: ""