apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels: { app: mysql }
spec:
  clusterIP: None   # headless for stable DNS to pods
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector: { app: mysql }